export interface IMenuItem {
  label: string;
  iconName: string;
  subMenuHeading?: string;
  currentlySelected?: string;
  subMenuItems?: {
    label: string;
  }[];
}

export const headerMenuItems: IMenuItem[] = [
  {
    label: "Your data in YouTube",
    iconName: "Profile",
  },
  {
    label: "Appearance",
    iconName: "HalfMoon",
    subMenuHeading: "Appearance",
    currentlySelected: "Light Theme",
    subMenuItems: [{ label: "Dark Theme" }, { label: "Light Theme" }],
  },
  {
    label: "Language",
    iconName: "Language",
    subMenuHeading: "Choose Your Language",
    currentlySelected: "English (US)",
    subMenuItems: [
      { label: "Afrikaans" },
      { label: "Azarbaycan" },
      { label: "Bahasa Indonesia" },
      { label: "Bahasa Malaysia" },
      { label: "Bosanki" },
      { label: "Catala" },
      { label: "Cestina" },
      { label: "Dansk" },
      { label: "Deutsch" },
      { label: "Eesti" },
      { label: "English (Indian)" },
      { label: "AfrikaansEnglish (UK)" },
      { label: "English (US)" },
      { label: "Espanol (Espana)" },
      { label: "Espanol (Latinoamérica)" },
      { label: "Latinoamérica (US)" },
      { label: "Euskara" },
      { label: "Filipino" },
      { label: "Francais" },
      { label: "Francais (Canada)" },
      { label: "Galego" },
      { label: "Hrvatski" },
      { label: "isiZulu" },
      { label: "Islenka" },
      { label: "Italiano" },
      { label: "Kiswahili" },
      { label: "Latviešu valoda" },
      { label: "Magyar" },
      { label: "Nederlands" },
      { label: "Norsk" },
    ],
  },
  {
    label: "Location",
    iconName: "Globe",
    subMenuHeading: "Choose Your Location",
    currentlySelected: "India",
    subMenuItems: [
      { label: "Algeria" },
      { label: "Argentina" },
      { label: "Austraia" },
      { label: "Austria" },
      { label: "Azerbaijan" },
      { label: "Bahrain" },
      { label: "Bangladesh" },
      { label: "Belarus" },
      { label: "Belgium" },
      { label: "Bolivia" },
      { label: "Bosnia and Herzegovina" },
      { label: "Brazil" },
      { label: "Bulgaria" },
      { label: "Cambodia" },
      { label: "Costa Rica" },
      { label: "Croatia" },
      { label: "Cyprus" },
      { label: "Czechia" },
      { label: "Denmark" },
      { label: "Dominican Rebuplic" },
      { label: "Ecuador" },
      { label: "Egypt" },
      { label: "El Salvador" },
      { label: "Estonia" },
      { label: "Finland" },
      { label: "France" },
      { label: "Georgia" },
      { label: "Germany" },
      { label: "Ghana" },
      { label: "Greece" },
      { label: "Guatemala" },
      { label: "Honduras" },
      { label: "Hong Kong" },
      { label: "Hungary" },
      { label: "Iceland" },
      { label: "India" },
      { label: "Indonesia" },
      { label: "Iraq" },
      { label: "Ireland" },
      { label: "Israel" },
      { label: "Italy" },
    ],
  },
  {
    label: "Restricted Mode",
    iconName: "Restriction",
    subMenuHeading: "Restricted Mode",
    currentlySelected: "",
  },

  {
    label: "Keyboard Shortcuts",
    iconName: "Keyboard",
  },
  {
    label: "Settings",
    iconName: "Settings",
  },
  {
    label: "Help",
    iconName: "Help",
  },
  {
    label: "Send Feedback",
    iconName: "Send feedback",
  },
];
